version: "3.2"

services:
  dev:
    container_name: e-ballot
    image: paritytech/ci-linux:production
    working_dir: /var/www/e-ballot
    ports:
      - "9944:9944"
    environment:
      - CARGO_HOME=/var/www/e-ballot/.cargo
    volumes:
      - .:/var/www/e-ballot
      - type: bind
        source: ./.local
        target: /root/.local
    command: bash -c "cargo build --release && ./target/release/e-ballot --dev --ws-external"
